name = "testapp-auth"
main = "workers/auth.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
RP_NAME = "TestApp Authentication"
RP_ID = "localhost"
ORIGIN = "http://localhost:8787"

[env.production]
[env.production.vars]
SENDGRID_API_KEY = "your_production_sendgrid_api_key"
FROM_EMAIL = "noreply@yourdomain.com"

[env.development]
[env.development.vars]
SENDGRID_API_KEY = "your_dev_sendgrid_api_key"
FROM_EMAIL = "noreply@yourdomain.com"

[[d1_databases]]
binding = "DB"
database_name = "testapp-database"
database_id = "ae1bafef-5bf9-4a9d-9773-14c2b017d2be"

[[kv_namespaces]]
binding = "SESSIONS"
id = "496281ad0a90470aa04a5338a4681f7b"