name = "data-manager-auth"
main = "cloudflare-worker-d1.js"
compatibility_date = "2024-12-01"

# D1データベース設定
[[d1_databases]]
binding = "TESTAPP_DB"
database_name = "testapp-database"
database_id = "ae1bafef-5bf9-4a9d-9773-14c2b017d2be"

# R2バケット設定
[[r2_buckets]]
binding = "QUESTA_BUCKET"
bucket_name = "questa"

# 環境変数
[vars]
JWT_SECRET = "questa-jwt-secret-2024"
